version: '3'
services:
  shadowsocks:
    
    ports:
      - 8888:8888
     
 
    build:
      context: .
        
      dockerfile: Dockerfile
    environment:
      - METHOD=rc4 # 加密方法
      - PASSWORD=170826  # 密码
   
    restart: always