version: '3'
services:
  ss:
    
    ports:
      - 80:80
     
 
    build:
      context: .
        
      dockerfile: Dockerfile
    environment:
      - METHOD=rc4 # 加密方法
      - PASSWORD=170826  # 密码
   
    restart: always