version: '3'
services:
  shadowsocks:
    
    ports:
      - 443:443
     
 
    build:
      context: .
        
      dockerfile: Dockerfile
    environment:
      - METHOD=rc4-md5 # 加密方法
      - PASSWORD=170826  # 密码
   
    restart: always